# Generated by Django 4.2.5 on 2023-10-10 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_pedido_latitude_pedido_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='coordenadas',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
