# Generated by Django 4.2.5 on 2023-10-14 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0004_pedido_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='preco_cooler',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
