# Generated by Django 4.2.5 on 2023-10-08 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cooler', '0001_initial'),
        ('bebida', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCooler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('bebida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bebida.bebida')),
                ('cooler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooler.cooler')),
            ],
        ),
    ]
